### ISSUE TITLE
OcExecTask does not finish

### ISSUE THREAD

**Issue by A-Wiedemann** [g3force/gradle-oc#3]
Dear g3force,

thank you for your plugin.

We found a small issue in OcExecTask. If the log of `oc import-image <service>:<version> --from=<url> --reference-policy=local --confirm` is very long, the gradle task _OcExecTask_ does not finish.

[tmp.txt](https://github.com/g3force/gradle-oc/files/5195954/tmp.txt)

**Comment by g3force** [comment]
The whole output of the oc command is read to memory in version 0.4.1, so it is probably a OOM issue.

I've changed the way the output is read in version 0.4.2. It is now read line-by-line on a separate thread. I have not yet checked if it works with very large outputs, though.

**Comment by g3force** [comment]
Tested successfully
